name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.0.0
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PAT }}
    - name: Setup Maven
      uses: stCarolas/setup-maven@v.4.5
      with:
        maven-version: 3.6.0
    - name: Build
      run:
        mvn clean install -DskipTests
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.0.0
      with:
        tags: phinzin/springboot-angular-docker:latest
        
